### ISSUE TITLE
Consider using jsii/superchain as your image

### ISSUE THREAD

**Issue by eladb** [udondan/jsii-publish#1]
[jsii/superchain](https://hub.docker.com/r/jsii/superchain) is the official build environment for jsii projects. I am wondering if perhaps you'd want to use that as your the base image for your Dockerfile.

**Comment by udondan** [comment]
Oh nice, hadn't seen that before. It's a bit heavy weighted though. 3 times the size of my image. What do you need git, docker, ruby, gcc etc for?

**Comment by RomainMuller** [comment]
We had an early `ruby` jsii runtime implementation, so we had to have a `ruby` to support that (but we have stashed it for now). I guess we could drop this (for now), but it'll probably come back in some future.

The bulk of the weight of the image is `dotnet` (and `mono`).

The upsides of using it is that you get to be guaranteed to have *all* tooling necessary (and tested) to build all supported 1st-party language implementations for `jsii` without having to do it yourself.

If you have suggestions to trim the image down and make it thinner, your contributions on [jsii/superchain](https://github.com/aws/jsii/tree/master/superchain) will be much appreciated!!

**Comment by udondan** [comment]
I'm still unhappy with the size but I'm actually using superchain myself in another build step since a while now. To optimize CI build time on my end I'm using superchain now as the parent image. :-)

@RomainMuller Is the gcc compiler really required in superchain? I was able to build all packages in this image here without. So that might be an attack point to shrink the size.

**Comment by RomainMuller** [comment]
Yeah we have no direct use for it so could try to prune...
