### ISSUE TITLE
Publishers for all jsii languages

### ISSUE THREAD

**Issue by eladb** [udondan/jsii-publish#2]
The [scripts](https://github.com/eladb/cdk-dynamo-table-viewer/tree/master/scripts) here can be used to publish to all jsii-supported package managers. They have been extracted from [aws-delivlib](https://github.com/awslabs/aws-delivlib) which is used by the AWS CDK and jsii for our release pipelines.

**Comment by udondan** [comment]
Thanks for sharing the scripts Elad. The aws-delivlib is, as the name suggests, tightly coupled to AWS. Your modifications in the dynamo viewer make more sense, but I just could not get the Maven publisher working. I'm probably just too stupid. I spent a full weekend wasting time with Maven until I gave up.

I then remembered GitHub released the [packages service](https://github.com/features/packages) at the last GitHub Universe. It instantly worked. No need for the usual Maven crap. No Jira ticket for creating a repo, no Domain verification with DNS entries. _Jeees..._ 🙄 I now even figured out you can just publish the package with `curl`, no `mvn deploy` needed.

Also, the package signing IMHO doesn't make much sense. Simply because I'll not ever put my actual GPG private key into any online CI tool. So I'd sign a package with a randomly generated key, which defeats the purpose. 

Very happy with the [maven publisher](https://github.com/udondan/jsii-publish/blob/master/scripts/publish/maven) now. 😸
